version: '3'

services:
  uaa:
    image: scg-demo-uaa:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"

  gateway:
    image: scg-demo-security-gateway:latest
    container_name: gateway
    expose:
        - "8080"
    ports:
        - "8080:8080"
    depends_on:
        - highscoreservice11
        - helloworldservice11
        - uaa

  db:
    container_name: db
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  helloworldservice11:
    container_name: helloworld
    build: helloworldservice11
    ports:
      - "8081:8081"
    depends_on:
      - db
    links:
      - db
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  highscoreservice11:
    container_name: highscores
    build: highscoreservice11
    ports:
      - "8082:8082"
    depends_on:
      - db
    links:
      - db
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - DATABASE_HOST=postgres

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.18
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
