version: '3'

services:
  helloworldservice11:
    build: helloworldservice11
    ports:
      - "8080:8080"

  highscoreservice11:
    build: highscoreservice11
    ports:
      - "8082:8082"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
